const express = require("express");
const dotenv = require("dotenv");
dotenv.config({ path: "./config/.env" });
const cors = require("cors");
const db = require("./config/db");
db();
const product = require("./routes/product-routes");
const auth = require("./routes/auth-routes");
const user = require("./routes/user-routes");
const order = require("./routes/order-routes");
const app = express();
app.use(express.json());
app.use(express.static("public/"));
app.use(cors());
app.use("/api/products", product);
app.use("/api/auth", auth);
app.use("/api/user", user);
app.use("/api/order", order);
app.listen(process.env.PORT || 5000, () => {
  console.log("server is running");
});
